name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * THU"
  workflow_dispatch:

jobs:
  test_library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install non-pip dependencies of the workflow call library
        run: |
          sudo apt install -y -qq imagemagick inkscape
      - name: Install the workflow call library
        run: |
          python3 -m pip install .[docs,lint,tests]
      - name: Run flake8 checks
        run: |
          python3 -m flake8 .
          python3 -m nbqa flake8 .
      - name: Run tests
        run: |
          python3 -m pytest tests
        env:
          RCLONE_CONFIG_COLAB_CLIENT_ID: "${{ secrets.RCLONE_CONFIG_COLAB_CLIENT_ID }}"
          RCLONE_CONFIG_COLAB_CLIENT_SECRET: "${{ secrets.RCLONE_CONFIG_COLAB_CLIENT_SECRET }}"
          RCLONE_CONFIG_COLAB_TOKEN: "${{ secrets.RCLONE_CONFIG_COLAB_TOKEN }}"
      - name: Warn if scheduled workflow is about to be disabled
        if: github.repository == 'fem-on-colab/open-in-colab-workflow' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci.yml
          days-elapsed: 50
